import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es" | "fr" | "de" | "pt" | "ar";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    title: "Hangman",
    subtitle: "Guess the word before it's too late!",
    startPlaying: "Start Playing",
    howToPlay: "How to Play:",
    instruction1: "Guess letters to reveal the hidden word",
    instruction2: "You have 6 chances to guess wrong",
    instruction3: "Win by guessing the word before it's too late!",
    chooseGroup: "Choose Your Group",
    selectDifficulty: "Select a difficulty level to start",
    levels: "Levels",
    level: "Level",
    group: "Group",
    hint: "Hint",
    remainingChances: "Remaining Chances",
    lettersUsed: "Letters used",
    congratulations: "Congratulations!",
    youWon: "You Won!",
    gameOver: "Game Over!",
    theWordWas: "The word was",
    playAgain: "Play Again",
    nextLevel: "Next Level",
    backToLevels: "Back to Levels",
    home: "Home",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    veryHard: "Very Hard",
    tutorialTitle: "Welcome to Hangman!",
    tutorialStep1Title: "Choose Your Group",
    tutorialStep1Desc: "Start by selecting a difficulty group (A-Z). Groups A-E are easy, F-N are medium, O-P are hard, and Q-Z are very hard!",
    tutorialStep2Title: "Complete Levels",
    tutorialStep2Desc: "Each group has 10 levels. Complete all levels in a group to unlock the next one!",
    tutorialStep3Title: "Guess the Word",
    tutorialStep3Desc: "Click letters to guess the word. You have 6 wrong guesses before the game is over. Use hints to help you!",
    tutorialStep4Title: "Progress & Win",
    tutorialStep4Desc: "Complete all levels to become a Hangman master! Your progress is saved automatically.",
    startTutorial: "Start Tutorial",
    skipTutorial: "Skip",
    nextStep: "Next",
    previousStep: "Previous",
    gotIt: "Got It!"
  },
  es: {
    title: "Ahorcado",
    subtitle: "¡Adivina la palabra antes de que sea tarde!",
    startPlaying: "Comenzar a Jugar",
    howToPlay: "Cómo Jugar:",
    instruction1: "Adivina letras para revelar la palabra oculta",
    instruction2: "Tienes 6 oportunidades para equivocarte",
    instruction3: "¡Gana adivinando la palabra antes de que sea tarde!",
    chooseGroup: "Elige Tu Grupo",
    selectDifficulty: "Selecciona un nivel de dificultad para comenzar",
    levels: "Niveles",
    level: "Nivel",
    group: "Grupo",
    hint: "Pista",
    remainingChances: "Oportunidades Restantes",
    lettersUsed: "Letras usadas",
    congratulations: "¡Felicitaciones!",
    youWon: "¡Ganaste!",
    gameOver: "¡Juego Terminado!",
    theWordWas: "La palabra era",
    playAgain: "Jugar de Nuevo",
    nextLevel: "Siguiente Nivel",
    backToLevels: "Volver a Niveles",
    home: "Inicio",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    veryHard: "Muy Difícil",
    tutorialTitle: "¡Bienvenido al Ahorcado!",
    tutorialStep1Title: "Elige Tu Grupo",
    tutorialStep1Desc: "Comienza seleccionando un grupo de dificultad (A-Z). Los grupos A-E son fáciles, F-N son medios, O-P son difíciles y Q-Z son muy difíciles!",
    tutorialStep2Title: "Completa Niveles",
    tutorialStep2Desc: "¡Cada grupo tiene 10 niveles. Completa todos los niveles de un grupo para desbloquear el siguiente!",
    tutorialStep3Title: "Adivina la Palabra",
    tutorialStep3Desc: "Haz clic en las letras para adivinar la palabra. Tienes 6 intentos incorrectos antes de que termine el juego. ¡Usa pistas para ayudarte!",
    tutorialStep4Title: "Progreso y Victoria",
    tutorialStep4Desc: "¡Completa todos los niveles para convertirte en un maestro del Ahorcado! Tu progreso se guarda automáticamente.",
    startTutorial: "Iniciar Tutorial",
    skipTutorial: "Saltar",
    nextStep: "Siguiente",
    previousStep: "Anterior",
    gotIt: "¡Entendido!"
  },
  fr: {
    title: "Pendu",
    subtitle: "Devinez le mot avant qu'il ne soit trop tard!",
    startPlaying: "Commencer à Jouer",
    howToPlay: "Comment Jouer:",
    instruction1: "Devinez les lettres pour révéler le mot caché",
    instruction2: "Vous avez 6 chances de vous tromper",
    instruction3: "Gagnez en devinant le mot avant qu'il ne soit trop tard!",
    chooseGroup: "Choisissez Votre Groupe",
    selectDifficulty: "Sélectionnez un niveau de difficulté pour commencer",
    levels: "Niveaux",
    level: "Niveau",
    group: "Groupe",
    hint: "Indice",
    remainingChances: "Chances Restantes",
    lettersUsed: "Lettres utilisées",
    congratulations: "Félicitations!",
    youWon: "Vous Avez Gagné!",
    gameOver: "Jeu Terminé!",
    theWordWas: "Le mot était",
    playAgain: "Rejouer",
    nextLevel: "Niveau Suivant",
    backToLevels: "Retour aux Niveaux",
    home: "Accueil",
    easy: "Facile",
    medium: "Moyen",
    hard: "Difficile",
    veryHard: "Très Difficile",
    tutorialTitle: "Bienvenue au Pendu!",
    tutorialStep1Title: "Choisissez Votre Groupe",
    tutorialStep1Desc: "Commencez par sélectionner un groupe de difficulté (A-Z). Les groupes A-E sont faciles, F-N sont moyens, O-P sont difficiles et Q-Z sont très difficiles!",
    tutorialStep2Title: "Complétez les Niveaux",
    tutorialStep2Desc: "Chaque groupe a 10 niveaux. Complétez tous les niveaux d'un groupe pour débloquer le suivant!",
    tutorialStep3Title: "Devinez le Mot",
    tutorialStep3Desc: "Cliquez sur les lettres pour deviner le mot. Vous avez 6 essais incorrects avant la fin du jeu. Utilisez les indices pour vous aider!",
    tutorialStep4Title: "Progrès et Victoire",
    tutorialStep4Desc: "Complétez tous les niveaux pour devenir un maître du Pendu! Votre progrès est sauvegardé automatiquement.",
    startTutorial: "Démarrer le Tutoriel",
    skipTutorial: "Passer",
    nextStep: "Suivant",
    previousStep: "Précédent",
    gotIt: "Compris!"
  },
  de: {
    title: "Galgenmännchen",
    subtitle: "Errate das Wort, bevor es zu spät ist!",
    startPlaying: "Spielen Beginnen",
    howToPlay: "Spielanleitung:",
    instruction1: "Errate Buchstaben, um das versteckte Wort zu enthüllen",
    instruction2: "Du hast 6 Versuche zu irren",
    instruction3: "Gewinne, indem du das Wort errätst, bevor es zu spät ist!",
    chooseGroup: "Wähle Deine Gruppe",
    selectDifficulty: "Wähle einen Schwierigkeitsgrad zum Starten",
    levels: "Stufen",
    level: "Stufe",
    group: "Gruppe",
    hint: "Hinweis",
    remainingChances: "Verbleibende Versuche",
    lettersUsed: "Verwendete Buchstaben",
    congratulations: "Glückwunsch!",
    youWon: "Du Hast Gewonnen!",
    gameOver: "Spiel Vorbei!",
    theWordWas: "Das Wort war",
    playAgain: "Nochmal Spielen",
    nextLevel: "Nächste Stufe",
    backToLevels: "Zurück zu Stufen",
    home: "Startseite",
    easy: "Einfach",
    medium: "Mittel",
    hard: "Schwer",
    veryHard: "Sehr Schwer",
    tutorialTitle: "Willkommen bei Galgenmännchen!",
    tutorialStep1Title: "Wähle Deine Gruppe",
    tutorialStep1Desc: "Beginne mit der Auswahl einer Schwierigkeitsgruppe (A-Z). Gruppen A-E sind einfach, F-N sind mittel, O-P sind schwer und Q-Z sind sehr schwer!",
    tutorialStep2Title: "Stufen Abschließen",
    tutorialStep2Desc: "Jede Gruppe hat 10 Stufen. Schließe alle Stufen in einer Gruppe ab, um die nächste freizuschalten!",
    tutorialStep3Title: "Errate das Wort",
    tutorialStep3Desc: "Klicke auf Buchstaben, um das Wort zu erraten. Du hast 6 falsche Versuche, bevor das Spiel vorbei ist. Nutze Hinweise zur Hilfe!",
    tutorialStep4Title: "Fortschritt & Gewinnen",
    tutorialStep4Desc: "Schließe alle Stufen ab, um ein Galgenmännchen-Meister zu werden! Dein Fortschritt wird automatisch gespeichert.",
    startTutorial: "Tutorial Starten",
    skipTutorial: "Überspringen",
    nextStep: "Weiter",
    previousStep: "Zurück",
    gotIt: "Verstanden!"
  },
  pt: {
    title: "Forca",
    subtitle: "Adivinhe a palavra antes que seja tarde demais!",
    startPlaying: "Começar a Jogar",
    howToPlay: "Como Jogar:",
    instruction1: "Adivinhe letras para revelar a palavra escondida",
    instruction2: "Você tem 6 chances de errar",
    instruction3: "Ganhe adivinhando a palavra antes que seja tarde!",
    chooseGroup: "Escolha Seu Grupo",
    selectDifficulty: "Selecione um nível de dificuldade para começar",
    levels: "Níveis",
    level: "Nível",
    group: "Grupo",
    hint: "Dica",
    remainingChances: "Chances Restantes",
    lettersUsed: "Letras usadas",
    congratulations: "Parabéns!",
    youWon: "Você Ganhou!",
    gameOver: "Fim de Jogo!",
    theWordWas: "A palavra era",
    playAgain: "Jogar Novamente",
    nextLevel: "Próximo Nível",
    backToLevels: "Voltar aos Níveis",
    home: "Início",
    easy: "Fácil",
    medium: "Médio",
    hard: "Difícil",
    veryHard: "Muito Difícil",
    tutorialTitle: "Bem-vindo à Forca!",
    tutorialStep1Title: "Escolha Seu Grupo",
    tutorialStep1Desc: "Comece selecionando um grupo de dificuldade (A-Z). Grupos A-E são fáceis, F-N são médios, O-P são difíceis e Q-Z são muito difíceis!",
    tutorialStep2Title: "Complete Níveis",
    tutorialStep2Desc: "Cada grupo tem 10 níveis. Complete todos os níveis de um grupo para desbloquear o próximo!",
    tutorialStep3Title: "Adivinhe a Palavra",
    tutorialStep3Desc: "Clique nas letras para adivinhar a palavra. Você tem 6 tentativas erradas antes do jogo acabar. Use dicas para ajudar!",
    tutorialStep4Title: "Progresso e Vitória",
    tutorialStep4Desc: "Complete todos os níveis para se tornar um mestre da Forca! Seu progresso é salvo automaticamente.",
    startTutorial: "Iniciar Tutorial",
    skipTutorial: "Pular",
    nextStep: "Próximo",
    previousStep: "Anterior",
    gotIt: "Entendi!"
  },
  ar: {
    title: "شنق",
    subtitle: "!خمن الكلمة قبل فوات الأوان",
    startPlaying: "ابدأ اللعب",
    howToPlay: ":كيفية اللعب",
    instruction1: "خمن الحروف للكشف عن الكلمة المخفية",
    instruction2: "لديك 6 فرص للخطأ",
    instruction3: "!اربح بتخمين الكلمة قبل فوات الأوان",
    chooseGroup: "اختر مجموعتك",
    selectDifficulty: "حدد مستوى الصعوبة للبدء",
    levels: "مستويات",
    level: "مستوى",
    group: "مجموعة",
    hint: "تلميح",
    remainingChances: "الفرص المتبقية",
    lettersUsed: "الحروف المستخدمة",
    congratulations: "!تهانينا",
    youWon: "!لقد فزت",
    gameOver: "!انتهت اللعبة",
    theWordWas: "الكلمة كانت",
    playAgain: "العب مرة أخرى",
    nextLevel: "المستوى التالي",
    backToLevels: "العودة إلى المستويات",
    home: "الصفحة الرئيسية",
    easy: "سهل",
    medium: "متوسط",
    hard: "صعب",
    veryHard: "صعب جدا",
    tutorialTitle: "مرحباً بك في لعبة الشنق!",
    tutorialStep1Title: "اختر مجموعتك",
    tutorialStep1Desc: "ابدأ باختيار مجموعة صعوبة (A-Z). المجموعات A-E سهلة، F-N متوسطة، O-P صعبة، و Q-Z صعبة جداً!",
    tutorialStep2Title: "أكمل المستويات",
    tutorialStep2Desc: "كل مجموعة تحتوي على 10 مستويات. أكمل جميع المستويات في مجموعة لفتح المجموعة التالية!",
    tutorialStep3Title: "خمن الكلمة",
    tutorialStep3Desc: "انقر على الحروف لتخمين الكلمة. لديك 6 محاولات خاطئة قبل انتهاء اللعبة. استخدم التلميحات للمساعدة!",
    tutorialStep4Title: "التقدم والفوز",
    tutorialStep4Desc: "أكمل جميع المستويات لتصبح خبيراً في لعبة الشنق! يتم حفظ تقدمك تلقائياً.",
    startTutorial: "ابدأ الدليل",
    skipTutorial: "تخطي",
    nextStep: "التالي",
    previousStep: "السابق",
    gotIt: "فهمت!"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};